db:
    image: wso2senai/wso2-base-container
stratos:
    image: stratos:4.0.0
private-paas:
    build: -t wso2senai/private-paas .
    command: 
    ports:
        - "9443:9443"
    links:
        - db
        - stratos